CC = g++
CFLAGS = -Wall -lGL -lGLU -lglut -lGLEW 

OBJ_DIR = obj
SRC_DIR = src
LIB_DIR = lib 
INC_DIR = inc

main: $(SRC_DIR)/main.cpp 
	$(CC) $(SRC_DIR)/main.cpp -o output $(CFLAGS) 
clean:
	rm output